FORMAT: 1A
HOST: http://apis.compasso.com.br/api/v1/

# Compasso API

Polls is a simple API allowing consumers to view polls and vote in them.

## Group Customers

### Customer [/customers/{id}/]

#### Query Customer [GET]

+ Parameters

    + id: `1234567890` (string) - The customer id.
    
+ Request

    + Headers

            Authorization: Bearer iapsdPdpsadpPdpadsnf
            
+ Response 200 (application/json)

     + Body
     
            {
                "id":"1234567890",
                "fullName": "João da Silva",
                "gender": "male",
                "email": "joao.silva@mycompany.com",
                "birthDate": "1992-12-30",
                "addresses": {
                    "id": "12345",
                    "primary": true,
                    "street": "Julio de Castilhos",
                    "buildingNumber": "123",
                    "complement": "7° Andar",
                    "neighborhood": "Sul",
                    "city": "Porto Alegre",
                    "state": "RS",
                    "postalCode": "00000000",
                    "country": "BR"
                },
                "phones": [{
                        "id": "123456",]
                        "primary": true,
                        "countryCode": "mobile",
                        "areaCode": "11",
                        "number": "994470532"
                    },
                    {
                        "id": "123456",
                        "primary": false,
                        "countryCode": "home",
                        "areaCode": "11",
                        "number": "21211111"
                    }
                ]
            }

+ Response 500 (application/json)

    Unexpected error.
    
    + Body

            {
                "errorCode": "999",
                "errorMessage": "Error description"
            }
            
+ Response 400 (application/json)

    Bad Request.
    
    + Body

            {
                "errorCode": "999",
                "errorMessage": "Error description"
            }
            
+ Response 401 (application/json)

    Unauthorized.
    
    + Body

            {
                "errorCode": "999",
                "errorMessage": "Error description"
            }
            
### Order [/orders/]

#### Create Order [POST]

+ Request

    + Headers

            Authorization: Bearer iapsdPdpsadpPdpadsnf
            
    + Body
    
            {
                  "id": "1234567890",
                  "submittedDate": null,
                  "status": "ok",
                  "site": "compasso",
                  "type": "DEFAULT",
                  "customerId": "123123123",
                  "subtotalPrice": 100,
                  "shippingPrice": 15,
                  "totalDiscounts": 1,
                  "totalPrice": 116
            }
    
+ Response 201 (application/json)
    
    + Body

            {
                "transactionId": "987654321"
            }
   
+ Response 500 (application/json)

    Unexpected error.
    
    + Body

            {
                "errorCode": "999",
                "errorMessage": "Error description"
            }